= todotxt-rs
ifndef::env-github[:icons: font]
ifdef::env-github[]
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

____
Ask more of your http://todotxt.org/[todo.txt] file
____

WARNING: This project is now archived. The todo.txt markup has been unmaintained for a few years now, and I believe it deserves https://github.com/todotxt/todo.txt/discussions/45[a few additions] to become really useful (for my taste anyway). If I am to work on a similar software again, I will also change the technical approach and rely on a parser combinator such as https://github.com/rust-bakery/nom[nom].

== What it is about

This tool aims at giving a practical front-end to the _todo.txt_ format.

.It is cut into two parts:
* a library crate responsible for the logic of interacting with the todo file
* a binary crate that exposes a CLI

Maybe more front-ends will come in the future, such as a desktop GUI, a webapp, or even a mobile app!

== Roadmap

Commands::
* [x] add task
* [x] mark task as done
* [x] remove task
* [ ] list tasks
* [ ] prioritize task
* [ ] deprioritize task
* [x] archive tasks
* [ ] update task
Other::
* [ ] manage a serialized configuration
* [ ] internationalization
* [ ] CI/CD

== Built using these great crates

* https://github.com/chronotope/chrono[chrono]
* https://github.com/clap-rs/clap[clap]
* https://github.com/mackwic/colored[colored]
