[package]
edition = "2018"
name = "todotxt-lib"
version = "0.1.0"
description = "Ask more of your todo.txt file - core library"
authors = ["Florent Nuttens"]
license = "MIT"

[dependencies]
chrono = "0.4"
